# Generated by Django 4.2.3 on 2023-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'verbose_name': 'Solicitudes', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobada'), (3, 'Rechazada')], verbose_name='Estatus'),
        ),
    ]
