# Generated by Django 4.2.3 on 2023-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='descripcion',
            field=models.TextField(default='Sin descripción', max_length=1000, verbose_name='Descripción'),
        ),
    ]
